AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ArreglaYA Metrics BE - Express on Lambda + HTTP API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
        STAGE: "prod"
        NODE_ENV: "production"

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/arreglaya/analytics/*'
      CodeUri: .
      Handler: dist/lambda.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          STAGE: 'prod'
          NODE_ENV: 'production'
          SSM_PATH_PREFIX: '/arreglaya/analytics/prod/db'
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: 
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
