AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ArreglaYA Metrics BE - Express on Lambda + HTTP API

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stage
  DBHost:
    Type: String
    Description: Database host
  DBUsername:
    Type: String
    Description: Database username
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
  DBName:
    Type: String
    Description: Database name
  UsersApiBaseUrl:
    Type: String
    Description: Users API base URL
  CoreHubApiKey:
    Type: String
    Description: Core Hub API key
    NoEcho: true
  CoreHubUrl:
    Type: String
    Description: Core Hub URL
  WebhookSecret:
    Type: String
    Description: Webhook secret
    NoEcho: true
  WebhookBaseUrl:
    Type: String
    Description: Webhook base URL

Conditions:
  IsProduction: !Equals [!Ref Stage, 'prod']

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
        STAGE: "prod"
        NODE_ENV: "production"

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      DisableExecuteApiEndpoint: false

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/arreglaya/analytics/*'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/arreglaya/analytics/${Stage}/*'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/arreglaya/analytics/${Stage}/db/*'
      CodeUri: .
      Handler: dist/lambda-handler.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          STAGE: !Ref Stage
          NODE_ENV: !If [IsProduction, 'production', 'development']
          DB_HOST: !Ref DBHost
          DB_USERNAME: !Ref DBUsername
          DB_PASSWORD: !Ref DBPassword
          DB_NAME: !Ref DBName
          USERS_API_BASE_URL: !Ref UsersApiBaseUrl
          CORE_HUB_API_KEY: !Ref CoreHubApiKey
          CORE_HUB_URL: !Ref CoreHubUrl
          WEBHOOK_SECRET: !Ref WebhookSecret
          WEBHOOK_BASE_URL: !Ref WebhookBaseUrl
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
