name: Deploy to Stage

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AWS_REGION: us-east-1 # Change this to your target region
  STACK_NAME: arreglaya-analytics-stage # Your CloudFormation stack name for stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Deploy to AWS Lambda
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: |
        npm install -g aws-cdk
        cdk deploy --require-approval never \
          --context stage=stage \
          --context environment=stage
      env:
        NODE_ENV: stage