name: Deploy to Stage

on:
  push:
    branches: [develop]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      # Install dependencies and build TypeScript
      - run: npm ci
      - run: npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN_STAGE }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: aws-actions/setup-sam@v2
      
      # Delete the stack if it exists in ROLLBACK_COMPLETE state
      - name: Delete failed stack
        run: |
          if aws cloudformation describe-stacks --stack-name arreglaya-analytics-be-stage 2>&1 | grep -q 'ROLLBACK_COMPLETE'; then
            aws cloudformation delete-stack --stack-name arreglaya-analytics-be-stage
            aws cloudformation wait stack-delete-complete --stack-name arreglaya-analytics-be-stage
          fi
        continue-on-error: true
      
      - run: sam build --use-container
      
      # Deploy with secure parameters
      - name: Get SSM Parameters
        id: ssm
        env:
          PARAM_PATH: /arreglaya/analytics/stage/db
        run: |
          {
            set -e  # Exit on any error
            set +x  # Disable command echo
            
            # Función para obtener y enmascarar parámetro de SSM
            get_ssm_param() {
              local param_name=$1
              local value
              value=$(aws ssm get-parameter --name "$PARAM_PATH/$param_name" --with-decryption --query 'Parameter.Value' --output text)
              # Enmascarar el valor inmediatamente
              echo "::add-mask::$value"
              # Escribir al GITHUB_ENV usando la sintaxis de delimitador
              echo "$2<<EOF" >> $GITHUB_ENV
              echo "$value" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            }
            
            # Obtener y almacenar parámetros de forma segura
            get_ssm_param 'host' 'DB_HOST'
            get_ssm_param 'username' 'DB_USERNAME'
            get_ssm_param 'password' 'DB_PASSWORD'
            get_ssm_param 'name' 'DB_NAME'
            get_ssm_param 'users-api-base-url' 'USERS_API_BASE_URL'
            get_ssm_param 'core-hub-api-key' 'CORE_HUB_API_KEY'
            get_ssm_param 'core-hub-url' 'CORE_HUB_URL'
            get_ssm_param 'webhook-secret' 'WEBHOOK_SECRET'
            get_ssm_param 'webhook-base-url' 'WEBHOOK_BASE_URL'

            echo "::debug::SSM parameters retrieved and masked successfully"
          } 2>/dev/null

      - name: Deploy SAM application
        env:
          SAM_CLI_TELEMETRY: 0
        run: |
          set +x # Disable command echo
          
          echo "::debug::Starting SAM deployment..."
          
          # Deploy using masked environment variables directly
          sam deploy \
            --stack-name arreglaya-analytics-be-stage \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides \
              Stage=stage \
              DBHost="$DB_HOST" \
              DBUsername="$DB_USERNAME" \
              DBPassword="$DB_PASSWORD" \
              DBName="$DB_NAME" \
              UsersApiBaseUrl="$USERS_API_BASE_URL" \
              CoreHubApiKey="$CORE_HUB_API_KEY" \
              CoreHubUrl="$CORE_HUB_URL" \
              WebhookSecret="$WEBHOOK_SECRET" \
              WebhookBaseUrl="$WEBHOOK_BASE_URL" \
            --no-fail-on-empty-changeset \
            --force-upload
          
          echo "::debug::SAM deployment completed"

      - name: Add STAGE environment variable
        run: |
          FUNCTION_NAME=$(aws lambda list-functions --query "Functions[?contains(FunctionName, 'arreglaya-analytics-be-stage')].FunctionName" --output text)
          if [ ! -z "$FUNCTION_NAME" ]; then
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --environment "Variables={STAGE=stage,DEPLOYMENT_TIMESTAMP=$(date +%s)}"
            echo "STAGE variable added to Lambda"
          fi
